### ISSUE TITLE
Incorrect value for field "master_itemid": maximum dependent items count reached.

### ISSUE THREAD

**Issue by hardwareadictos** [rickkbarbosa/covid9-monitor#10]
Just having this issue trying to Add the template you updated yesterday to my zabbix server:

Incorrect value for field "master_itemid": maximum dependent items count reached.

Seems i can add it to my clients but not on the server.

Thanks in advance :)

**Comment by rickkbarbosa** [comment]
Hey! 


The template was tested on Zabbix 4.0.18 and  above.

Wich Zabbix version have you trying to use?

Cheers,

**Comment by hardwareadictos** [comment]
Hey! Using 4.0.4

Fixed it by setting /usr/share/zabbix/include/defines.inc.php:define('ZBX_DEPENDENT_ITEM_MAX_COUNT',        999);  to 2999.

Seems my zabbix install is alil bit old.

Thank you :)

**Comment by rickkbarbosa** [comment]
Thanks for your info. Think it's the best way :)

Also, to decrease number of dependant items, "total cases" item prototype has changed to calculated item [a few commits before](https://github.com/rickkbarbosa/covid9-monitor/commit/389504884874aa94631bf9ed9fcf21c706c9b12e)  .


Cheers,

**Comment by hardwareadictos** [comment]
I left this issue as solved. Thanks a lot :)
