### ISSUE TITLE
Random issues displaying per country stats

### ISSUE THREAD

**Issue by hardwareadictos** [rickkbarbosa/covid9-monitor#12]
Hi again.

Regarding to this: https://github.com/rickkbarbosa/covid9-monitor/issues/10

Finnally updated to Zabbix 4.0.18.

Seems that randomly, zabbix isnt aquiring the data correctly.

Yesterday was working quite fine all day. Today i discovered this:

![Screenshot 2020-03-15 at 17 18 41](https://user-images.githubusercontent.com/20403906/76705548-243eed80-66e1-11ea-9d92-8c8d67122643.png)

Seems that no other country is being reported a part from china. Yesterday on latest data section all coutries were listed. 

On Grafana i can only see total stats and worldmap (cannot see data either on the map):

![Screenshot 2020-03-15 at 17 21 47](https://user-images.githubusercontent.com/20403906/76705603-98799100-66e1-11ea-9fa4-2e6d8514b527.png)

As reported on zabbix ¨latest data¨ theres no graphical reports for individual countries:

Seems that covid data isnt reporting anything (maybe thats where the issue is coming from):

![Screenshot 2020-03-15 at 17 44 19](https://user-images.githubusercontent.com/20403906/76706041-ef349a00-66e4-11ea-98f0-ebacdb6b2121.png)

Here is the zabbix server log:

[zabbix_server.log](https://github.com/rickkbarbosa/covid9-monitor/files/4334515/zabbix_server.log)

Scripts seems to be working fine also, here you have the outputs:

[corona_scripts_output.txt](https://github.com/rickkbarbosa/covid9-monitor/files/4334536/corona_scripts_output.txt)

Same output on the frontend:

![Screenshot 2020-03-15 at 17 51 51](https://user-images.githubusercontent.com/20403906/76706164-c7920180-66e5-11ea-88be-e1f523dd1df1.png)

Thanks in advance for your help again. Really interested on implement this on my environment :)

**Comment by rickkbarbosa** [comment]
I believe it's related with Zabbix update interval.

I has suffered with something like this when I tried apply too short pooling times (e.g. each 1 minute). 
By default I'm using 30 min on update interval, once information on Worldometer isn't real-time updated. :)


Please let me know if it helped you.  I hope so :) .

**Comment by hardwareadictos** [comment]
Yes. Seems to work fine now.

Yesterday it didnt work. Only seeing a little display glitches. Lets wait to see if they dissappear along the day:

On affected countries something is traspassing my server names to the list:

![image](https://user-images.githubusercontent.com/20403906/76739223-34e87580-676c-11ea-8c31-600c9d610482.png)

On total cases i see doubled results (think that is fixed, have to update the clone):

![image](https://user-images.githubusercontent.com/20403906/76739435-7aa53e00-676c-11ea-90ae-d4282e156da4.png)

General stats doesnt seem to be displayed correctly:

![image](https://user-images.githubusercontent.com/20403906/76739941-5433d280-676d-11ea-84fe-e20d87f4f98c.png)

Thank you :)

**Comment by rickkbarbosa** [comment]
Hi, 

Grafana dashboard is able to handle with only one host on Zabbix. I didn't work with more zabbix hosts.

Your issues should be related with this condition.

Best regards,

**Comment by hardwareadictos** [comment]
But i always use same data source. The only zabbix server I have 😔

Is there any way of resetting all data collected by the template?

I already cleared it but same result.


Thanks in advance. 😊

**Comment by rickkbarbosa** [comment]
I mean one only host on your zabbix server :)

**Comment by hardwareadictos** [comment]
Thank you!

I just deleted all items from all my clients and cleared the template, readded it to only the server i have assigned the zabbix datasource on grafana and all works fine now.

Cheers :)

![image](https://user-images.githubusercontent.com/20403906/76957239-b596a580-6915-11ea-94e3-870c1ad30e36.png)
