### ISSUE TITLE
Help with the installation.

### ISSUE THREAD

**Issue by araneon** [rickkbarbosa/covid9-monitor#15]
Good afternoon, I first encountered Grafana, do not help me with instructions on how to set up a covid9 monitor in my home?

**Comment by VixenVix** [comment]
Witch part do you have problem with? What Linux distribution do you use?
https://grafana.com/docs/grafana/latest/installation/requirements/

**Comment by araneon** [comment]
Thanks for the answer, I installed Grafana on one server in place with Zabbix (CentOS7).  I can’t understand how to add COVID-19 monitoring in Grafana?

**Comment by VixenVix** [comment]
First you need some data in Zabbix. Do you have working monitoring in Zabbix and accumulate data?
Then you have to integrate Zabbix with Grafana https://blog.zabbix.com/configuring-grafana-with-zabbix/8007/. 
The last part is creating Dashboard importing .json file from this project https://github.com/rickkbarbosa/covid9-monitor/blob/master/grafana_dashboard.json

**Comment by araneon** [comment]
I added the content of the .zhsion file to the dashboard properties and when I save I get an error.
Template initialization error
Data source named $ {DS_ZABBIX} not found

**Comment by VixenVix** [comment]
You missed one step. As I wrote before: "integrate Zabbix with Grafana https://blog.zabbix.com/configuring-grafana-with-zabbix/8007/" <- this is adding a  data source, step 3. There's also a link to a video on this site.

**Comment by araneon** [comment]
Integration of Zabbix with Grafana I carried out.
![Zabbix_1](https://user-images.githubusercontent.com/18113701/77287797-7a1a2380-6ce7-11ea-9436-451155705c6b.png)
The next steps I'm doing.
1) Create a new dashboard and select its properties
![Zabbix_2](https://user-images.githubusercontent.com/18113701/77288024-fdd41000-6ce7-11ea-84a5-5926938d4e10.png)
2) In the properties I select JSON Model
![Zabbix_3](https://user-images.githubusercontent.com/18113701/77288066-12b0a380-6ce8-11ea-84ec-0de0e105d4f0.png)
3) And in the code window, I paste the text from grafana_dashboard.json
![Zabbix_4](https://user-images.githubusercontent.com/18113701/77288092-1ba17500-6ce8-11ea-920d-a4fdfbe32e59.png)
(In the screenshot, the text is JSON before the change)
Are these the right steps or am I doing something wrong?

**Comment by araneon** [comment]
I assume that on the Zabbix server itself I need to attach the template to the host? I just don’t understand which host it needs to be connected to.

**Comment by VixenVix** [comment]
Yes, attach it to any host, for example zabbix server itself. But only to one host. And don't add new dashboard, **import** it.

**Comment by araneon** [comment]
Thanks a lot !!!
I connected the panel, but now it’s not clear what is wrong with the data, there is none!
![Zabbix_1](https://user-images.githubusercontent.com/18113701/77324642-20861900-6d28-11ea-8b6b-92575d44460f.png)
![Zabbix_2](https://user-images.githubusercontent.com/18113701/77324652-2419a000-6d28-11ea-9199-f6566b2993f8.png)
![Zabbix_3](https://user-images.githubusercontent.com/18113701/77324663-27ad2700-6d28-11ea-8f1f-d43ba9b982e7.png)
![Zabbix_4](https://user-images.githubusercontent.com/18113701/77324669-2bd94480-6d28-11ea-8225-d35ea26377d3.png)
![Zabbix_5](https://user-images.githubusercontent.com/18113701/77324690-309df880-6d28-11ea-884e-feb248c14599.png)
![Zabbix_6](https://user-images.githubusercontent.com/18113701/77324702-34317f80-6d28-11ea-8a76-9358a9d0e218.png)

I have a suspicion that something had to be done with Python scripts.
Tell me, do I need to do something separately with them or just put it in the /usr/lib/zabbix/externalscripts folder?

**Comment by araneon** [comment]
And another moment, I don’t know, maybe this is important.
I apparently use Python 2.7 on CentOS
This was reported to me by the PIP when I completed:
sudo pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by VixenVix** [comment]
I have python 2.7. Now worries. You have no data in zabbix. Login to zabbix and check, also check zabbix logs in /var/log. You need these files in /usr/lib/zabbix/externalscripts:
covid19_affectedcountries.py
covid19_status.py
iban.csv

Also set Timeout=30 in zabbix_server.conf

Then run `python covid19_affectedcountries.py` manually in a console. After that `python covid19_status.py`. If you see some data then it should work in zabbix. If not check zabbix logs.

**Comment by araneon** [comment]
When you manually start both scripts, the first message appears:
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
The covid19_affectedcountries.py script freezes for a few seconds and produces:
{
    "data": [
        {
            "{#COUNTRY_NAME}": "China",
            "{#COUNTRY_IBAN}": "CHN"
        },
        {
            "{#COUNTRY_NAME}": "Italy",
            "{#COUNTRY_IBAN}": "ITA"
        },
        {
            "{#COUNTRY_NAME}": "USA",
            "{#COUNTRY_IBAN}": "USA"
        },
        {
            "{#COUNTRY_NAME}": "Spain",
            "{#COUNTRY_IBAN}": "ESP"
        },
and so much data.

The covid19_status.py script freezes a little less and produces:
{"China": {"TotalCases": 81093, "NewCases": "+ 39", "TotalDeaths": 3270.0, "NewDeaths": 9.0, "TotalRecovered": 72703.0, "ActiveCases": 5120, "Serious, Critical" : 1749.0, "Tot \ u00a0Cases \ / 1M pop": 56.0}, "Italy": {"TotalCases": 63927, "NewCases": "+ 4.789", "TotalDeaths": 6077.0, "NewDeaths": 601.0, "TotalRecovered ": 7432.0," ActiveCases ": 50418," Serious, Critical ": 3204.0," Tot \ u00a0Cases \ / 1M pop ": 1057.0},
and so much data.
In Zabbix there is only the data of the script covid19_status.py
![Zabbix_1](https://user-images.githubusercontent.com/18113701/77346787-d9a81b80-6d47-11ea-97a7-459f94f70d3a.png)

**Comment by araneon** [comment]
I also found the next moment!
![Zabbix_1](https://user-images.githubusercontent.com/18113701/77400300-fed67180-6dbb-11ea-9754-56a47c15148a.png)
![Zabbix_2](https://user-images.githubusercontent.com/18113701/77400321-03028f00-6dbc-11ea-875a-acd1d9182bb6.png)

**Comment by araneon** [comment]
It turned out to get data.
But the data is not coming to Grafan.
![Zabbix_1](https://user-images.githubusercontent.com/18113701/77405851-d010c900-6dc4-11ea-89ac-ca9e97205359.png)
![Zabbix_2](https://user-images.githubusercontent.com/18113701/77405860-d1da8c80-6dc4-11ea-9712-7256cc562335.png)
![Zabbix_3](https://user-images.githubusercontent.com/18113701/77405869-d3a45000-6dc4-11ea-8c9b-20021344e2b6.png)

**Comment by araneon** [comment]
Sorry, it turns out I had to wait more and the data will go to Grafana.
Thank you very much for your help!

**Comment by VixenVix** [comment]
You've mixed python-requests library in your system with the one from pip install but I'm glad you've made it :)

**Comment by araneon** [comment]
Indeed, I reinstalled the python libraries several times, tried to run it all through python 3, but it turned out that it works for python 2. Thank you very much for your help!
