### ISSUE TITLE
Cast error while getting data for numerals vs strings

### ISSUE THREAD

**Issue by VixenVix** [rickkbarbosa/covid9-monitor#17]
I've got these cast errors:

` 25851:20200321:215932.303 error reason for "Zabbix server:covid19.data[NewCases, "Switzerland"]" changed: Value "+1,131" of type "string" is not suitable for value type "Numeric (float)"
 25850:20200321:222932.988 error reason for "Zabbix server:covid19.data[NewCases, "Switzerland"]" changed: Value "+1,132" of type "string" is not suitable for value type "Numeric (float)"
 25850:20200321:222932.988 error reason for "Zabbix server:covid19.data[NewCases, "USA"]" changed: Value "+5,403" of type "string" is not suitable for value type "Numeric (float)"
`

Zabbix 4.4.6
Python 2.7.16

**Comment by rickkbarbosa** [comment]
Hey,


I believe I could fix it [here](https://github.com/rickkbarbosa/covid9-monitor/commit/654fef7094c4e0f11a59107d60544287f21adf54) .


Could you retry and tell me how looks like?

Cheers,

**Comment by VixenVix** [comment]
Looks fixed, thanks :)
