### ISSUE TITLE
Totals for Recoveries are wrong

### ISSUE THREAD

**Issue by VixenVix** [rickkbarbosa/covid9-monitor#18]
![image](https://user-images.githubusercontent.com/28901578/77246257-d87ecd80-6c25-11ea-8d6e-313e99014f4d.png)

**Comment by rickkbarbosa** [comment]
Hi,

Thanks for report. I'm supressed total in graph [to simplify visualization](https://github.com/rickkbarbosa/covid9-monitor/commit/d116a38b0bbd2a5ca7d39adcbe49458412e1afdf).


Thanks,

**Comment by VixenVix** [comment]
Thanks. I tested it and it broke some graphs. I'm not sure if it only me or global issue.

![image](https://user-images.githubusercontent.com/28901578/77421019-60eaa300-6dcb-11ea-8b70-7aa141618b2b.png)
