### ISSUE TITLE
failed to load data

### ISSUE THREAD

**Issue by deltonr** [rickkbarbosa/covid9-monitor#19]
![image](https://user-images.githubusercontent.com/8696189/77829552-81836780-7101-11ea-9591-3cb66f4a85e2.png)

In zabbix the data is displayed correctly, but not in the granfana dashboard.
The version of zabbix is 4.4.
debian 10 64bit
Grafana 6.7.1

**Comment by VixenVix** [comment]
It's not a problem with this project. Check the steps here #15
