### ISSUE TITLE
 No tables found matching pattern '.+'

### ISSUE THREAD

**Issue by williamnormandia** [rickkbarbosa/covid9-monitor#22]
Hello, I'm having a problem with the scripts, it started happening 4 days ago.

[root@acsc-zabbix covid9-monitor]# ./covid19_status.py
Traceback (most recent call last):
  File "./covid19_status.py", line 35, in <module>
    df = pd.read_html(str(soup), index_col=1, thousands=r',', flavor="bs4")[0]
  File "/usr/lib64/python2.7/site-packages/pandas/io/html.py", line 1094, in read_html
    displayed_only=displayed_only)
  File "/usr/lib64/python2.7/site-packages/pandas/io/html.py", line 916, in _parse
    raise_with_traceback(retained)
  File "/usr/lib64/python2.7/site-packages/pandas/io/html.py", line 898, in _parse
    tables = p.parse_tables()
  File "/usr/lib64/python2.7/site-packages/pandas/io/html.py", line 221, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "/usr/lib64/python2.7/site-packages/pandas/io/html.py", line 570, in _parse_tables
    .format(patt=match.pattern))
ValueError: No tables found matching pattern '.+'

**Comment by RonniHolst** [comment]
Have the same issue ..

**Comment by support-capensis** [comment]
Same for me ...

**Comment by samyscoub** [comment]
Same for me ...

**Comment by creizlein** [comment]
Same problem here, any update on how to fix this? using python3

**Comment by creizlein** [comment]
I did fixed it, there are 2 diff problems, one with BeautifulSoup that needs uppercase tags and the second one that you need to remove totals by continents, otherwise you get several "Total" rows.

Below is the modified lines:
```
r = requests.get(url, headers=header).text
r = re.sub(r'<.*?>', lambda g: g.group(0).upper(), str(r))
r = re.sub(r'<TBODY CLASS="BODY_CONTINENTS">(.|\n)*?<\/TBODY>', '', r)
```

**Comment by creizlein** [comment]
Below is a much efficient replace that just discards everything that is not needed
Takes 10 less seconds in my Raspi.

```
r = requests.get(url, headers=header).text
r = re.sub(r'.*(<table id="main_table_countries_today".*?>.*?<\/table>).*', r'\1', r, flags=re.DOTALL)
r = re.sub(r'<tbody class="body_continents">.*?<\/tbody>', '', r, flags=re.DOTALL)
r = re.sub(r'<.*?>', lambda g: g.group(0).upper(), r)
```

**Comment by rickkbarbosa** [comment]
Hi!

Sorry for the delay.

Thanks @creizlein . I've append your code on new commit.


Best,

**Comment by soroush-babaei** [comment]
Can you tell me why it is not working properly?
It all gives the error No tables found matching

        tables = pd.read_html(finall, match= "Religion")
        if tables !=[]:
            print(tables)
            print('-'*30)
        else:
            tables.append(country)
            print(country + ' is NOT Processed')
            print('-'*30)
